---
title: "What is going on with crime in Phoenix?"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

```{r setup, include=FALSE}

knitr::opts_chunk$set( echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.width = 12, 
                      fig.height = 10 )

rm( list = ls() )

```


```{r, echo = FALSE, eval = TRUE}

# clear workspace.
rm( list = ls() )

# load libraries.
library( dplyr )
library( tidyr )
library( ggplot2 )
library( scales )
library( forecast )
library( openxlsx )


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# Crime incidents.

# get the crime incidents data file.
url <- "https://www.phoenixopendata.com/dataset/cc08aace-9ca9-467f-b6c1-f0879ab1a358/resource/0ce3411a-2fc6-4302-a33f-167f68608a20/download/crimestat.csv"
crime.data <- read.csv( url, as.is = TRUE, header = TRUE )
crime.data <- na.omit( crime.data )

# Help with formating the text.
n.cases <- dim( crime.data )[1]

# Clean up the dates.
date.vec <- strptime( crime.data$OCCURRED.ON, format="%m/%d/%Y %H:%M" )
crime.data$year   <- format( date.vec, format="%Y" )
crime.data$month  <- format( date.vec, format="%B" )
crime.data$day365 <- format( date.vec, format="%j" )
crime.data$week   <- format( date.vec, format="%V" )

# Drop cases for the most recent month.
crime.data <- crime.data[ ! ( 
  crime.data$month == format( Sys.Date(), format="%B" ) &
  crime.data$year == format( Sys.Date(), format="%Y" ) 
  ) , ]

# Use dplyr() to create an object that is the daily count of crimes.
crimes.by.day <- 
  crime.data %>% 
  select( year, month, day365 ) %>%   
  filter( !is.na( day365 ) ) %>% 
  group_by( year, month, day365 ) %>% 
  summarize( counts = n() ) %>% 
  ungroup() %>% 
  mutate( day.time = seq( 1, length( counts ) ) ) %>% 
  select( counts, day.time ) %>% 
  mutate( days = 
            seq( 
              as.Date( head( strptime( crime.data$OCCURRED.ON, format="%m/%d/%Y %H:%M" ) ) )[1], 
              as.Date( tail( strptime( crime.data$OCCURRED.ON, format="%m/%d/%Y %H:%M" ) ) )[6], 
              length.out = length( counts ) ) ) %>% 
  arrange( day.time )

crimes.by.day <- as.data.frame( crimes.by.day )

# Use dplyr() to create an object that is the monthly count of crimes.
crimes.by.month <- 
  crime.data %>% 
  select( year, month ) %>%   
  filter( year != 2015 ) %>%  
  filter( !is.na( year ) ) %>% 
  group_by( year, month ) %>% 
  summarize( counts = n() ) %>% 
  spread( year, counts ) %>% 
  arrange( match( month, month.name ) ) %>% 
  select( !month )


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# Population data for Phoenix.

# get the population data to create the rates.
pop.data <- read.xlsx(
  "https://www2.census.gov/programs-surveys/popest/tables/2010-2019/cities/totals/SUB-IP-EST2019-ANNRES-04.xlsx",
  colNames = TRUE,
  startRow = 4
)

# Find the row with the data for Phoenix.
grep("Phoenix", pop.data[,1])

# It is the 55th row in the object. So, we need to pull that row.
phoenix.pop <-  pop.data[55,]
phoenix.pop

# Now, we only need the data for 2016-2019.
phoenix.pop <- phoenix.pop[-c(1:9)]
phoenix.pop

# Just add the difference for each year until you get the actual demographic data..
phoenix.pop.2020 <- phoenix.pop[4] + phoenix.pop[4] - phoenix.pop[3]
phoenix.pop.2021 <- phoenix.pop.2020 + phoenix.pop[4] - phoenix.pop[3]
phoenix.pop.2022 <- phoenix.pop.2021 + phoenix.pop[4] - phoenix.pop[3]
phoenix.pop.data <- as.numeric( c( phoenix.pop, phoenix.pop.2020, phoenix.pop.2021, phoenix.pop.2022 ) )


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# Create the rates using the population data.

# now, calculate the crime rate. Crime rate is calculated as the count of crimes divided by the population size, then multipled by 100,000.

crime.rates <- as.data.frame( crimes.by.month )

for ( i in 1: dim( crime.rates )[2] ){
 crime.rates[,i] <- ( crime.rates[,i] / phoenix.pop.data[i] ) * 100000
}

# Create the time series.
monthly.crime.rate.by.year <- ts(
  matrix( as.matrix( crimes.by.month ), ncol = 1 ), 
  start=c( 2016, 1 ), 
  end=c( as.numeric( tail( names( crimes.by.month ), n=1 ) ), 12 ), frequency=12
)

monthly.crime.rate.by.year %>% 
  ggseasonplot(
   year.labels=FALSE,
   main = "Plot of Monthly Crime Count by Years for Phoenix" ) + 
  scale_y_continuous(label = comma) +
  theme_gray() 

```

