---
title: "R 2 Phoenix"
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

Welcome to [R 2 Phoenix]()! This site is dedicated to analyzing data from the [City of Phoenix](https://www.phoenix.gov/) open [data](https://www.phoenixopendata.com/) portal.

[City of Phoenix](https://www.phoenix.gov/) open [data](https://www.phoenixopendata.com/) portal? It is a repository for data that the city collects and makes available. As of last check, there were over 50 datasets available. The site is well organized, so I would encourage you to open an new tab and check it out. The site has a [tips](https://www.phoenixopendata.com/pages/tips) page with a good intro to site navigation and how it is maintained.  

*This* site uses the data from the [data portal](https://www.phoenixopendata.com/) to examine various topics (see below). For each topic, there are a set of questions that are examined using data from the portal. ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/R2PhX/issues) page. **Enjoy!**  


<br><br>

#### **Crime in Phoenix**  

<br>

##### [Why look at crime incidents using the portal?](https://jacobtnyoung.github.io/R2PhX/projects/PHXcrime.html)  

<br>

##### [What is going on with crime in Phoenix? (well, let's look!)](https://jacobtnyoung.github.io/R2PhX/projects/PHXcrime_trends.html)

<br>

##### [(More on) What is going on with crime (**types**) in Phoenix?](https://jacobtnyoung.github.io/R2PhX/projects/PHXcrime_types.html)

<br>

##### [Is **Homicide** on the rise in Phoenix?](https://jacobtnyoung.github.io/R2PhX/projects/PHXcrime_homicide.html)

<br>

##### [What "went down" with crime in Phoenix in 2020?](https://jacobtnyoung.github.io/R2PhX/projects/PHXcrime_types_2020.html)

<br>

##### Are police shootings by police officers increasing in Phoenix? (and other questions...) (CURRENTLY BEING REPAIRED)

<br>

<br><br>

#### **Other Questions/Topics**  

<br>

##### [When it's hot in Phoenix, do people go to the heat shelter? Let's take a look!](https://jacobtnyoung.github.io/R2PhX/projects/PHX_heat_shelter_2020.html)

<br>

***Please*** report any corrections or comments to the [Issues](https://github.com/jacobtnyoung/R2PhX/issues) page. Thanks!

<br><br>

###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***